require("mwm.plugins-setup")
require("mwm.core.options")
require("mwm.core.keymaps")
require("mwm.core.colorscheme")
require("mwm.plugins.comment")
-- require("mwm.plugins.nvim-tree")
require("mwm.plugins.lualine")
require("mwm.plugins.telescope")
require("mwm.plugins.nvim-cmp")
require("mwm.plugins.lsp.mason")
require("mwm.plugins.lsp.lspsaga")
require("mwm.plugins.lsp.lspconfig")
require("mwm.plugins.lsp.null-ls")
require("mwm.plugins.autopairs")
require("mwm.plugins.treesitter")
require("mwm.plugins.gitsigns")
